In [8]:
import numpy as np

In [2]:
import pandas as pd

In [6]:
x=[1,2,3,4,5,6]
x

[1, 2, 3, 4, 5, 6]

In [9]:
np.array(x)

array([1, 2, 3, 4, 5, 6])

In [12]:
b=np.random.rand(20)
b

array([0.232988  , 0.27423095, 0.13912671, 0.8713371 , 0.96344801,
       0.8731884 , 0.20315118, 0.63091686, 0.35506239, 0.61895043,
       0.32451555, 0.99812977, 0.27151376, 0.09840393, 0.136388  ,
       0.3801843 , 0.66080412, 0.51339161, 0.49192299, 0.58775995])

In [15]:
b=np.random.randint(1,20,19)
b

array([ 5,  9, 18, 10,  1,  3, 16, 12, 10,  4,  1,  5, 10, 12, 11, 10,  7,
       16,  9], dtype=int32)

In [18]:
#maximum valu
np.max(b)

np.int32(18)

In [19]:
#minimum
np.min(b)

np.int32(1)

In [28]:
rand_int=np.random.randint(1,50,20)
rand_int

array([42, 20,  1,  4, 14, 21, 17,  8, 23, 31, 18, 46, 35, 15, 23, 36, 24,
       20, 34, 15], dtype=int32)

In [29]:
#finding the index of maximum numner
rand_int.argmax()

np.int64(11)

In [30]:
#showing the position?index of minimum 
rand_int.argmin()

np.int64(2)

In [31]:
#displaying shape
ele=rand_int.reshape(4,5)

In [34]:
s=ele.shape
s

(4, 5)

In [38]:
arr=np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
#to sclect any element from array
arr[14]

np.int64(14)

In [40]:
arr[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#here we will see value from 1 to 10 each 2 element distance by 2
arr[1:10:2]

array([1, 3, 5, 7, 9])

In [44]:
arr2=arr[2:11]
arr2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr2[0:4]=99
arr2

array([99, 99, 99, 99,  6,  7,  8,  9, 10])

In [47]:
arr

array([ 0,  1, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
arr=np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
arr2=arr[2:11].copy()

In [51]:
arr2[2:4]=99
arr2

array([ 2,  3, 99, 99,  6,  7,  8,  9, 10])

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
arr2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#to see the value of a 2d matrix
arr2d[1,1]


np.int64(25)

In [59]:
arr2d[1:3,1:3]

array([[25, 30],
       [40, 45]])

In [60]:
arr=np.arange(1,11)

In [61]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr<5


array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [63]:
arr[arr<5]

array([1, 2, 3, 4])

In [64]:
#Operation in array
arr=np.arange(1,10)

In [65]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [67]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [68]:
arr*arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [69]:
arr/0

C:\Users\Asus\AppData\Local\Temp\ipykernel_3792\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [70]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [71]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [72]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [73]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])